# Generated by Django 5.1.3 on 2024-12-10 08:00

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwoFAUserApp', '0002_alter_twofauser_groups_alter_twofauser_phone_number_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofauser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='twofauser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='twofa_user_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
