# Generated by Django 5.1.3 on 2024-12-10 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwoFAUserApp', '0002_alter_twofauser_groups_alter_twofauser_phone_number_and_more'),
        ('movieApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TwoFAUserApp.twofauser'),
        ),
    ]
