# Generated by Django 5.1.1 on 2024-10-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='castmembers',
            old_name='castMember',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='castmembers',
            name='lastname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
