# Generated by Django 5.1.1 on 2024-10-26 10:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0003_castmembers_createdat_castmembers_createdby_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='castmembers',
            name='movieStar',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='duration',
            field=models.DurationField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='seasonsNo',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='castmembers',
            name='character',
            field=models.TextField(max_length=255),
        ),
        migrations.CreateModel(
            name='MovieMakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('modifiedAt', models.DateTimeField(auto_now=True)),
                ('contentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieApp.content')),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdMovieMakers', to=settings.AUTH_USER_MODEL)),
                ('modifiedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedMovieMakers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
