# Generated by Django 5.1.3 on 2024-12-10 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0003_userinfo_groups_userinfo_is_active_userinfo_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='gender',
        ),
    ]
