# Generated by Django 5.0 on 2024-12-15 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0004_remove_userinfo_age_remove_userinfo_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
