# Generated by Django 5.0 on 2024-12-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0005_alter_code_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='nr',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
