# Generated by Django 5.0 on 2024-12-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0008_castmembers_contentnr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castmembers',
            name='contentId',
            field=models.IntegerField(),
        ),
    ]
