# Generated by Django 5.0 on 2024-12-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0009_alter_castmembers_contentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviemakers',
            name='contentNr',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moviemakers',
            name='nr',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moviemakers',
            name='contentId',
            field=models.IntegerField(),
        ),
    ]
